package org.acme.insurance;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label(value = "Driver")
public class Driver  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Age")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer age;
    
    @org.kie.api.definition.type.Label(value = "Credit Score")
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.Integer creditScore;
    
    @org.kie.api.definition.type.Label(value = "DL Number")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String dlNumber;
    
    @org.kie.api.definition.type.Label(value = "Driver Name")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String driverName;
    
    @org.kie.api.definition.type.Label(value = "Number of Accidents")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.Integer numberOfAccidents;
    
    @org.kie.api.definition.type.Label(value = "Number of Tickets")
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.Integer numberOfTickets;
    
    @org.kie.api.definition.type.Label(value = "SSN")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String ssn;

    public Driver() {
    }

    public Driver(java.lang.String driverName, java.lang.Integer age, java.lang.String ssn, java.lang.String dlNumber, java.lang.Integer numberOfAccidents, java.lang.Integer numberOfTickets, java.lang.Integer creditScore) {
        this.driverName = driverName;
        this.age = age;
        this.ssn = ssn;
        this.dlNumber = dlNumber;
        this.numberOfAccidents = numberOfAccidents;
        this.numberOfTickets = numberOfTickets;
        this.creditScore = creditScore;
    }


    
    public java.lang.Integer getAge() {
        return this.age;
    }

    public void setAge(  java.lang.Integer age ) {
        this.age = age;
    }
    
    public java.lang.Integer getCreditScore() {
        return this.creditScore;
    }

    public void setCreditScore(  java.lang.Integer creditScore ) {
        this.creditScore = creditScore;
    }
    
    public java.lang.String getDlNumber() {
        return this.dlNumber;
    }

    public void setDlNumber(  java.lang.String dlNumber ) {
        this.dlNumber = dlNumber;
    }
    
    public java.lang.String getDriverName() {
        return this.driverName;
    }

    public void setDriverName(  java.lang.String driverName ) {
        this.driverName = driverName;
    }
    
    public java.lang.Integer getNumberOfAccidents() {
        return this.numberOfAccidents;
    }

    public void setNumberOfAccidents(  java.lang.Integer numberOfAccidents ) {
        this.numberOfAccidents = numberOfAccidents;
    }
    
    public java.lang.Integer getNumberOfTickets() {
        return this.numberOfTickets;
    }

    public void setNumberOfTickets(  java.lang.Integer numberOfTickets ) {
        this.numberOfTickets = numberOfTickets;
    }
    
    public java.lang.String getSsn() {
        return this.ssn;
    }

    public void setSsn(  java.lang.String ssn ) {
        this.ssn = ssn;
    }

    public String toString()
    {
        StringBuilder sBuilder = new StringBuilder("Driver  properties =");
        sBuilder.append("\n\tdriverName : "+driverName);
        sBuilder.append("\n\tdlNumber : " +dlNumber);
        sBuilder.append("\n\tage : "+age);
        sBuilder.append("\n\t# accidents : " +numberOfAccidents);
        sBuilder.append("\n\t# tickets : " +numberOfTickets);
        sBuilder.append("\n\tSSN : " +ssn);
        sBuilder.append("\n\t# creditScore : " +creditScore);
        return sBuilder.toString();
    }
}
